version: '2'
services:
  operations-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /home/docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ethieTieCh8ahv
    ports:
      - "3306:3307"

  operations-app:
    build: .
    ports:
      - 5000:5001
    environment:
      FINERACT_DATASOURCE_CORE_HOST: 127.0.0.1
      SPRING_PROFILES_ACTIVE: bb
    depends_on:
      - http://localhost/3307
